---
- hosts: all

  become: yes
  become_method: sudo

  vars:
    server_name: localhost

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes

  roles:
    - webserver
    - database
    - git